// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RVBARBER.Data;

#nullable disable

namespace RVBARBER.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250630111320_AddOpeningHoursTable")]
    partial class AddOpeningHoursTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("RVBARBER.Models.OpeningHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("AfternoonClose")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AfternoonOpen")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("MorningClose")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("MorningOpen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OpeningHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AfternoonClose = new TimeSpan(0, 0, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 0, 0, 0, 0),
                            DayOfWeek = 0,
                            IsClosed = true,
                            MorningClose = new TimeSpan(0, 0, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            AfternoonClose = new TimeSpan(0, 0, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 0, 0, 0, 0),
                            DayOfWeek = 1,
                            IsClosed = true,
                            MorningClose = new TimeSpan(0, 0, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            AfternoonClose = new TimeSpan(0, 19, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 14, 0, 0, 0),
                            DayOfWeek = 2,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 12, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            AfternoonClose = new TimeSpan(0, 0, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 0, 0, 0, 0),
                            DayOfWeek = 3,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 21, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            AfternoonClose = new TimeSpan(0, 19, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 14, 0, 0, 0),
                            DayOfWeek = 4,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 12, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            AfternoonClose = new TimeSpan(0, 19, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 14, 0, 0, 0),
                            DayOfWeek = 5,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 12, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            AfternoonClose = new TimeSpan(0, 0, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 0, 0, 0, 0),
                            DayOfWeek = 6,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 16, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("RVBARBER.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAppuntamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Totale")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrattamentiJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RVBARBER.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RVBARBER.Models.Reservation", b =>
                {
                    b.HasOne("RVBARBER.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
