// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RVBARBER.Data;

#nullable disable

namespace RVBARBER.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222103828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RVBARBER.Models.Closure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("AfternoonClose")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("AfternoonOpen")
                        .HasColumnType("time");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("MorningClose")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("MorningOpen")
                        .HasColumnType("time");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Closures");
                });

            modelBuilder.Entity("RVBARBER.Models.OpeningHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("AfternoonClose")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("AfternoonOpen")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("MorningClose")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("MorningOpen")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("OpeningHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AfternoonClose = new TimeSpan(0, 0, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 0, 0, 0, 0),
                            DayOfWeek = 0,
                            IsClosed = true,
                            MorningClose = new TimeSpan(0, 0, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            AfternoonClose = new TimeSpan(0, 0, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 0, 0, 0, 0),
                            DayOfWeek = 1,
                            IsClosed = true,
                            MorningClose = new TimeSpan(0, 0, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            AfternoonClose = new TimeSpan(0, 19, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 14, 0, 0, 0),
                            DayOfWeek = 2,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 12, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            AfternoonClose = new TimeSpan(0, 0, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 0, 0, 0, 0),
                            DayOfWeek = 3,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 21, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            AfternoonClose = new TimeSpan(0, 19, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 14, 0, 0, 0),
                            DayOfWeek = 4,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 12, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            AfternoonClose = new TimeSpan(0, 19, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 14, 0, 0, 0),
                            DayOfWeek = 5,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 12, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            AfternoonClose = new TimeSpan(0, 0, 0, 0, 0),
                            AfternoonOpen = new TimeSpan(0, 0, 0, 0, 0),
                            DayOfWeek = 6,
                            IsClosed = false,
                            MorningClose = new TimeSpan(0, 16, 0, 0, 0),
                            MorningOpen = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("RVBARBER.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barbiere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAppuntamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("datetime2");

                    b.Property<double>("Durata")
                        .HasColumnType("float");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Totale")
                        .HasColumnType("float");

                    b.Property<string>("TrattamentiJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RVBARBER.Models.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurataMinuti")
                        .HasColumnType("int");

                    b.Property<string>("NomeTrattamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prezzo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("RVBARBER.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RVBARBER.Models.Reservation", b =>
                {
                    b.HasOne("RVBARBER.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
